#!/usr/bin/perl

use strict;
use lib qw(/usr/lib/libDrakX);

use standalone;     #- warning, standalone must be loaded very first, for 'explanations'

use common;
use AdminPanel::Shared;
use AdminPanel::Services::services;
use log;

use yui;

my $wm_icon = "/usr/share/mcc/themes/default/service-mdk.png";

yui::YUI::app()->setApplicationTitle(N("Services and daemons"));
yui::YUI::app()->setApplicationIcon($wm_icon);

AdminPanel::Services::services::servicePanel();

