#!/usr/bin/perl

use lib qw(/usr/lib/libDrakX);

use common qw(N);

use AdminPanel::Users::GUsers;

my $userMan = AdminPanel::Users::GUsers->new({icon => "/usr/share/icons/userdrake.png",
                                              name => N("Mageia Users Management Tool"),});
$userMan->start();

1;
