#!/usr/bin/perl
# Copyright 2013 Matteo Pasotti
#
# This file is part of hostmanager
#
# hostmanager is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# hostmanager is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with AdminPanel.  If not, see <http://www.gnu.org/licenses/>.
use Modern::Perl 2011;
use autodie;
use AdminPanel::Hosts::GHosts;

use yui;

my $wm_icon = "/usr/lib/libDrakX/icons/IC-Dhost-48.png"; 

yui::YUI::app()->setApplicationTitle("Manage hosts definitions");
yui::YUI::app()->setApplicationIcon($wm_icon);

my $hostMan = AdminPanel::Hosts::GHosts->new();
$hostMan->start();

1;
