#!/usr/bin/perl
# vim: set et ts=4 sw=4:
# Copyright 2015-2017 Angelo Naselli
#
# This file is part of manatools
# and it is a script to test the module template
#
# mana_mt is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# mana_mt is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with ManaTools.  If not, see <http://www.gnu.org/licenses/>.
#

use ManaTools::Module::ModuleTemplate;

use yui;


my $mt = ManaTools::Module::ModuleTemplate->new({
});

$mt->start();

1;
