#!/usr/bin/perl
# vim: set et ts=4 sw=4:
# Copyright 2013 - 2015 Matteo Pasotti
#                  2015 Angelo Naselli
#
# This file is part of manatools
#
# manaproxy is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# manaproxy is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with ManaTools.  If not, see <http://www.gnu.org/licenses/>.
use Modern::Perl '2011';
use autodie;
use ManaTools::Module::Proxy;

use yui;

my $wm_icon = "/usr/share/mcc/themes/default/drakproxy-mdk.png";
my $wm_name = "Proxies configuration";

yui::YUI::app()->setApplicationTitle($wm_name);
yui::YUI::app()->setApplicationIcon($wm_icon);

my $proxyMan = ManaTools::Module::Proxy->new({
				icon => $wm_icon,
				name => $wm_name
			});
$proxyMan->start();

1;
