#!/usr/bin/perl
# vim: set et ts=4 sw=4:
# Copyright 2014 - 2015 Angelo Naselli
#
# This file is part of manatools
#
# manatools is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# manatools is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with ManaTools.  If not, see <http://www.gnu.org/licenses/>.
use ManaTools::Module::Users;
use ManaTools::Shared::Locales;
use yui;

my $cmdline    = new yui::YCommandLine;
my $locale_dir = undef;
my $pos        = $cmdline->find("--locales-dir");
if ($pos > 0)
{
    $locale_dir = $cmdline->arg($pos+1);
}
my $loc = ManaTools::Shared::Locales->new(
    domain_name => 'manatools',
    dir_name    => $locale_dir,
);

my $userMan = ManaTools::Module::Users->new({
    name => $loc->N("Mageia Add Users Tool"),
});

$userMan->addUserDialog(1);

1;
