#!/usr/bin/perl
# vim: set et ts=4 sw=4:
# Copyright 2013-2017 Matteo Pasotti
#           2015-2017 Angelo Naselli
#
# This file is part of manatools
#
# manadm is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# manadm is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with ManaTools.  If not, see <http://www.gnu.org/licenses/>.
use Modern::Perl '2011';
use autodie;

use ManaTools::Shared;
use ManaTools::Shared::Locales;
use ManaTools::Module::DisplayManager;

use yui;

my $dmanager = ManaTools::Module::DisplayManager->new();

$dmanager->start();

1;
