#!/usr/bin/perl
# vim: set et ts=4 sw=4:
# Copyright 2014 - 2015 Angelo Naselli
#
# This file is part of manatools
#
# manaservice is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# manaservice is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with ManaTools.  If not, see <http://www.gnu.org/licenses/>.
use strict;

use ManaTools::Module::Services;
use ManaTools::Shared::Locales;

my $loc = ManaTools::Shared::Locales->new(domain_name => 'libDrakX-standalone');

my $serviceMan = ManaTools::Module::Services->new({icon => "/usr/share/mcc/themes/default/service-mdk.png",
                                                          name => $loc->N("Services and daemons"),});
$serviceMan->start();

1;
