#!/usr/bin/perl
# Copyright 2014 - 2015 Angelo Naselli
#
# This file is part of proxymanager thus adminpanel
#
# proxymanager is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# proxymanager is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with AdminPanel.  If not, see <http://www.gnu.org/licenses/>.
use strict;

use AdminPanel::Module::LogViewer;

my $logviewer = AdminPanel::Module::LogViewer->new({icon => "/usr/share/mcc/themes/default/logdrake-mdk.png",
                                                    });
$logviewer->start();

1;
