#!/usr/bin/perl

use lib qw(/usr/lib/libDrakX);

use common qw(N);

use AdminPanel::Module::Users;

my $userMan = AdminPanel::Module::Users->new({icon => "/usr/share/icons/userdrake.png",
                                              name => N("Mageia Add Users Tool"),});
$userMan->addUserDialog(1);

1;
