#!/usr/bin/perl

use AdminPanel::Module::Users;
use AdminPanel::Shared::Locales;

my $loc = AdminPanel::Shared::Locales->new(domain_name => 'userdrake');

my $userMan = AdminPanel::Module::Users->new({icon => "/usr/share/icons/userdrake.png",
                                              name => $loc->N("Mageia Add Users Tool"),});

$userMan->addUserDialog(1);

1;
