#!/usr/bin/perl
# vim: set et ts=4 sw=4:
#    Copyright 2012 Steven Tucker
#    Copyright 2013 - 2015 Matteo Pasotti
#    Copyright 2014 - 2015 Angelo Naselli
#
#    This file is part of manatools
#
#    ManaTools is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 2 of the License, or
#    (at your option) any later version.
#
#    ManaTools is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with ManaTools.  If not, see <http://www.gnu.org/licenses/>.

package mpan::CommandLine;

use Moose;
extends 'ManaTools::Shared::GUI::CommandLine';

use ManaTools::Shared::Locales;

my $loc = ManaTools::Shared::Locales->new();

has 'devel' => (
    is            => 'ro',
    isa           => 'Bool',
    documentation => $loc->N('Developers mode'),
);

no Moose;
__PACKAGE__->meta->make_immutable;


1;

use strict;
use warnings;
use diagnostics;
use ManaTools::Privileges;
use ManaTools::SettingsReader;
use ManaTools::MainDisplay;
use mpan::CommandLine;

use yui;

my $cmdline = mpan::CommandLine->new_with_options();

my $settings = getSettings();

if ($cmdline->devel() > 0) {
    print $loc->N("== Development mode ON ==") . "\n";
}
else {
    ask_for_authentication($settings->{priv_method}) if is_root_capability_required();
}

my $mainWin = new ManaTools::MainDisplay();
while (1) {
    my $launch = $mainWin->start();

    if ($launch) {
        $mainWin->destroy();
        $launch->start();
    }
    else {
        $mainWin->destroy();
        last;
    }
    $mainWin->setupGui();
}


# mpan settings
sub getSettings {
    my ($self) = @_;

    # yui commandline parser
    my $confDir = $cmdline->conf_dir() || "/etc";
    chop $confDir if substr($confDir, -1) eq '/';
    $confDir .= '/mpan';

    # configuration file name
    my $fileName = "$confDir/settings.conf";
    return new ManaTools::SettingsReader({fileName => $fileName});
}

=pod

=head1 main

       main launcher

=cut

1;
