#!/usr/bin/perl
# Copyright 2013 Matteo Pasotti
#
# This file is part of proxymanager thus adminpanel
#
# proxymanager is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# proxymanager is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with AdminPanel.  If not, see <http://www.gnu.org/licenses/>.
use Modern::Perl '2011';
use autodie;
use AdminPanel::Module::Proxy;

use yui;

my $wm_icon = "/usr/share/mcc/themes/default/drakproxy-mdk.png"; 
my $wm_name = "Proxies configuration";

yui::YUI::app()->setApplicationTitle($wm_name);
yui::YUI::app()->setApplicationIcon($wm_icon);

my $proxyMan = AdminPanel::Module::Proxy->new({
				icon => $wm_icon,
				name => $wm_name
			});
$proxyMan->start();

1;
